Repository hypercerts-org/hypercerts-api, pull requests merged in 2025-02, with the labels that each got.

#236 fix: order-deletion
  src/controllers/MarketplaceController.ts
Labels: bug

#238 Implement contract signature verification
  package.json
  pnpm-lock.yaml
  src/lib/safe/signature-verification/SafeSignatureVerifier.ts
  src/lib/safe/signature-verification/SignatureVerifierStrategy.ts
  vitest.config.ts
Labels: bug, enhancement

#239 Push to PRD
  .github/workflows/ci-test-unit.yml
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/client/chainFactory.ts
  src/client/evmClient.ts
  src/client/rpcClientFactory.ts
  src/commands/CommandFactory.ts
  src/commands/SafeApiCommand.ts
  src/commands/UserUpsertCommand.ts
  src/controllers/BlueprintController.ts
  src/controllers/MarketplaceController.ts
  src/lib/rpcProviders/customEthersJsonRpcProvider.ts
  src/lib/safe/SafeApiKitStrategy.ts
  src/lib/safe/safe-rpc-urls.ts
  src/lib/safe/signature-verification/SafeSignatureVerifier.ts
  src/lib/safe/signature-verification/SignatureVerifierStrategy.ts
  src/lib/safe/signature-verification/UserUpsertSignatureVerifier.ts
  src/services/SupabaseDataService.ts
  src/utils/constants.ts
  src/utils/getRpcUrl.ts
  src/utils/getTokenPriceInUSD.ts
  src/utils/verifyAuthSignedData.ts
  src/utils/waitForTxThenMintBlueprint.ts
  test/client/chainFactory.test.ts
  test/client/evmClient.test.ts
  test/client/rpcClientFactory.test.ts
  test/lib/rpcProviders/customEthersJsonRpcProvider.test.ts
  test/safe-signatures/SafeSignatureVerifier.test.ts
  test/utils/verifyAuthSignedData.test.ts
  vitest.config.ts
Labels: enhancement

#249 fix(graphql): filter on collections not working
  src/graphql/schemas/resolvers/baseTypes.ts
  src/graphql/schemas/resolvers/collectionResolver.ts
  src/services/SupabaseDataService.ts
  test/safe-signatures/SafeSignatureVerifier.test.ts
  vitest.config.ts
Labels: bug

#259 Separate metadata image fetching from metadata query
  src/graphql/schemas/resolvers/baseTypes.ts
  src/graphql/schemas/resolvers/fractionResolver.ts
  src/graphql/schemas/resolvers/hyperboardResolver.ts
  src/graphql/schemas/resolvers/hypercertResolver.ts
  src/graphql/schemas/resolvers/metadataResolver.ts
  src/graphql/schemas/resolvers/orderResolver.ts
  src/graphql/schemas/resolvers/salesResolver.ts
  src/graphql/schemas/typeDefs/metadataTypeDefs.ts
  src/services/MetadataImageService.ts
  src/services/SupabaseCachingService.ts
Labels: enhancement

#245 Add health check to TSOA routes
  src/controllers/MonitoringController.ts
  src/index.ts
  test/controllers/MonitoringController.test.ts
Labels: enhancement

#262 Fix/ambiguous metadata id error
  src/services/SupabaseCachingService.ts
Labels: bug

#254 Allowlist claim response cache refresh
  package.json
  pnpm-lock.yaml
  src/__generated__/routes/routes.ts
  src/__generated__/swagger.json
  src/client/supabase.ts
Labels: bug
